### ISSUE TITLE
Arch Linux Build Error : /usr/bin/ld: <artificial>:(.text+XXXXX): undefined reference to `lua_XXXXX'

### ISSUE THREAD

**Issue by siuhamlop** [DerpyProjectGroup/topaz#741]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When compiling using Arch Linux I got bunch of errors after 100% (Starting to build topaz_game)
![Screenshot_20210924_165912](https://user-images.githubusercontent.com/11884769/134648223-e50e4863-ea4b-491c-b72b-fc84ea924f72.png)

**Comment by zach2good** [comment]
Looks like you don't have a correct (or any) lua library installed, which is why it can't find the references. I don't know how package management works on arch, but we use luajit 2.0, which is what you should be trying to install

**Comment by zach2good** [comment]
We have install instructions specifically for arch, did you use those (and they no longer work), or did you deviate from the steps?

**Comment by siuhamlop** [comment]
Thx for the quick reply, and yes I follow Land Sand Boat Arch install guide. I will try your method, thx.

**Comment by siuhamlop** [comment]
In github there is only 2 version to choose, 2.0.5 and latest 2.1, tried both no luck.

**Comment by zach2good** [comment]
2.0.5 will be fine, they're probably following [semver](https://semver.org/).

**Comment by zach2good** [comment]
Ah right, I read what you said. You could also try Lua 5.1, which is the same API

**Comment by zach2good** [comment]
You can also look in the CMake file where we look up LuaJIT (or Lua), and make sure it's looking in the right places for Arch: https://github.com/LandSandBoat/server/blob/base/cmake/FindLuaJIT.cmake

When CMake configures, it'll print out all of those paths so you can double check

**Comment by zach2good** [comment]
Should look something like this (taken from our Ubuntu 20.04 CI):
```
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so  
-- LuaJIT_FOUND: TRUE
-- LuaJIT_LIBRARY: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
-- LuaJIT_INCLUDE_DIR: /home/runner/work/server/server/ext/lua/include
```

**Comment by siuhamlop** [comment]
> You can also look in the CMake file where we look up LuaJIT (or Lua), and make sure it's looking in the right places for Arch: https://github.com/LandSandBoat/server/blob/base/cmake/FindLuaJIT.cmake
> 
> When CMake configures, it'll print out all of those paths so you can double check

Does it mean I can change Luajit to Lua?

**Comment by zach2good** [comment]
> Does it mean I can change Luajit to Lua?

In that file, yes. To whatever the library you're trying to link is named. I'd only try to use Lua instead of LuaJIT as an absolute emergency last resort. It hasn't been tested in years and everything we do is tailored around the use of LuaJIT

**Comment by siuhamlop** [comment]
> Should look something like this (taken from our Ubuntu 20.04 CI):
> 
> ```
> -- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so  
> -- LuaJIT_FOUND: TRUE
> -- LuaJIT_LIBRARY: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
> -- LuaJIT_INCLUDE_DIR: /home/runner/work/server/server/ext/lua/include
> ```

Got exactly this same output..but..sigh..no luck

**Comment by siuhamlop** [comment]
Oh, change to Lua 5.4....it works...thank you so much!!!

**Comment by zach2good** [comment]
I just ran up Arch in a container and everything built as expected, you may need to upgrade your package manager or something about your system:
```dockerfile
FROM archlinux:latest
WORKDIR /server
RUN echo "Y" | pacman -Syu
RUN echo "Y" | pacman -S sudo
RUN sudo echo "Y" | pacman -S git python3 python-pip gcc cmake make luajit zeromq openssl zlib mariadb
ADD . /server
RUN mkdir docker_build && cd docker_build && cmake .. && make -j $(nproc)  && cd .. && rm -r /server/docker_build
```
